include:
  - remote: 'https://gitlab.com/richardhj/deployment/raw/v1/.gitlab-ci.include.yml'

variables:
  SSH_USER: user
  SSH_HOST: test.uberspace.de
  SSH_DOCUMENT_ROOT: /var/www/virtual/user/contao-example.org/current
  URL: https://www.example.org


###########


save_database_dump:
  only:
    - schedules
  stage: deploy
  extends: .download_db_dump

composer_update:
  only:
    - schedules
  extends: .deployer
  script:
    - composer update --prefer-dist --no-progress --no-suggest
    - php deployer.phar deploy $DEPLOY_STAGE
