#!/bin/sh
#
# Imports the database given in the repository as database dump.
#
# This hook is invoked by git merge, which happens when a git pull
# is done on a local repository. The hook takes a single parameter,
# a status flag specifying whether or not the merge being done was
# a squash merge. This hook cannot affect the outcome of git merge
# and is not executed, if the merge failed due to conflicts.
#
# The file path is `.git/hooks/post-merge` to make things working.
# If things are not working and you are in doubt, 
# run `chmod +x .git/hooks/pre-commit`.
# If you are running MAMP on your Mac, use the path
# `/Applications/MAMP/Library/bin/mysql` for mysql.
#
# Author: Richard Henkenjohann <richardhenkenjohann@googlemail.com>
#

DBNAME=example
DBPATH=./var/sql

mysql $DBNAME < $DBPATH/dump.sql

exit 0
