#!/bin/sh
#
# Creates a database dump right before committing and adds it to
# the commit.
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# The file path is `.git/hooks/pre-commit` to make things working.
# If things are not working and you are in doubt, 
# run `chmod +x .git/hooks/pre-commit`.
# If you are running MAMP on your Mac, use the path
# `/Applications/MAMP/Library/bin/mysqldump` for mysqldump.
#
# In order to create a git-optimized dump, a search-replace pattern
# inspired by https://stackoverflow.com/a/19961480 is implemented.
# We do not use the --skip-extended-insert flag, as it would
# decrease the performance of the sql dump.
#
# To import the dump, use `mysql -u [user] -p[pass] mydb < mydb.sql`.
# Please consider to configure and `~/.my.cnf` file and to not pass
# the database credentials in this file.
#
# Hint: Consider to add `!/var/sql/` to your `.gitignore`.
#
# Author: Richard Henkenjohann <richardhenkenjohann@googlemail.com>
#

DBNAME=example
DBPATH=./var/sql
ARGS="--complete-insert --skip-comments --hex-blob --ignore-table=$DBNAME.tl_version --ignore-table=$DBNAME.tl_undo --ignore-table=$DBNAME.tl_session --ignore-table=$DBNAME.tl_search_index --ignore-table=$DBNAME.tl_search --ignore-table=$DBNAME.tl_log --ignore-table=$DBNAME.tl_cron"

mysqldump $ARGS $DBNAME | sed 's$VALUES ($VALUES\n  ($g' | sed 's$),($),\n  ($g' > $DBPATH/dump.sql

# This line instead for MAMP on Mac
# /Applications/MAMP/Library/bin/mysqldump $ARGS $DBNAME | sed 's$VALUES ($VALUES\'$'\n  ($g' | sed 's$),($),\'$'\n  ($g' > $DBPATH/dump.sql


git add $DBPATH/dump.sql
exit 0
